import type { Metadata } from "next";
import { Merriweather } from "next/font/google";
import "./globals.css";
import LightRays from "@/components/light-rays/light-rays";
import { ThemeProvider } from "@/context/theme-context";

const merriweather = Merriweather({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-merriweather",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="red">
      <body className={`${merriweather.variable} font-sans`}>
        <ThemeProvider>
          <LightRays
            raysOrigin="top-center"
            raysSpeed={1.5}
            lightSpread={0.8}
            rayLength={1.2}
            followMouse={true}
            mouseInfluence={0.1}
            noiseAmount={0.1}
            distortion={0.05}
          />

          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
